version: "3.3"

services:
  export:
    image: structurizr/cli:latest
    volumes:
      - ./:/usr/local/structurizr
    command: export -workspace app.dsl -format plantuml -output plantuml
  validate:
    image: structurizr/cli:latest
    volumes:
      - ./:/usr/local/structurizr
    command: validate -workspace app.dsl
  gen-image:
    build:
      context: ./plantuml
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./:/data
    command: plantuml -o "./build" "./*.puml"

